version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-jsr310
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: io.kubernetes:client-java-api
    versions:
    - 11.0.0
    - 11.0.1
  - dependency-name: com.alibaba:druid
    versions:
    - 1.2.4
    - 1.2.5
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
