apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: init
spec:
  containers:
    - name: container-1
      image: dbhammer/touchstone:latest
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "java -jar TouchstoneToolchain.jar /tmp/files/conf; while true; do sleep 30; done;" ]
      volumeMounts:
        - name: shared
          mountPath: /tmp/files
    - name: container-2
      image: dbhammer/touchstone:latest
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: shared
          mountPath: /tmp/files
  volumes:
    - name: shared
      configMap:
        name: config
        items:
          - key: tool.json
            path: conf
