
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ecnu.db.analyzer.online.adapter.pg.parser;

/** CUP generated interface containing symbol constants. */
public interface PgSelectSymbol {
  /* terminals */
  public static final int IS_NOT_NULL = 10;
  public static final int AND = 13;
  public static final int NE = 19;
  public static final int LT = 15;
  public static final int PLUS = 2;
  public static final int OR = 14;
  public static final int RPAREN = 7;
  public static final int IN = 22;
  public static final int DATE = 25;
  public static final int NOT = 9;
  public static final int LPAREN = 6;
  public static final int GT = 16;
  public static final int LE = 17;
  public static final int NOT_LIKE = 11;
  public static final int NOT_IN = 12;
  public static final int STRING = 24;
  public static final int FLOAT = 27;
  public static final int EOF = 0;
  public static final int DIV = 4;
  public static final int CANONICAL_COLUMN_NAME = 26;
  public static final int GE = 18;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int LIKE = 21;
  public static final int EQ = 20;
  public static final int INTEGER = 23;
  public static final int ISNULL = 8;
  public static final int MUL = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "DIV",
  "MUL",
  "LPAREN",
  "RPAREN",
  "ISNULL",
  "NOT",
  "IS_NOT_NULL",
  "NOT_LIKE",
  "NOT_IN",
  "AND",
  "OR",
  "LT",
  "GT",
  "LE",
  "GE",
  "NE",
  "EQ",
  "LIKE",
  "IN",
  "INTEGER",
  "STRING",
  "DATE",
  "CANONICAL_COLUMN_NAME",
  "FLOAT"
  };
}

